// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package siterouter

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Site-to-site tunnel configuration.
	// +kubebuilder:default:={}
	Tunnel Tunnel `json:"tunnel"`
	// Remote peer this router builds a tunnel to.
	// +kubebuilder:default:={}
	Peer Peer `json:"peer"`
	// Remote networks reachable over the tunnel. Must be disjoint from the cluster pod/service/join networks (validated by the controller).
	// +kubebuilder:default:={}
	RemoteCIDRs []string `json:"remoteCIDRs,omitempty"`
	// Optional extra static routes programmed on the router.
	// +kubebuilder:default:={}
	StaticRoutes []StaticRoute `json:"staticRoutes,omitempty"`
	// Optional BGP peering over the tunnel. Disabled by default.
	// +kubebuilder:default:={}
	Bgp BGP `json:"bgp"`
	// Explicit CPU and memory sizing for the router VM.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Boot-disk image source for the router VM.
	// +kubebuilder:default:={}
	Image Image `json:"image"`
	// Source CIDR allowed to reach the VyOS management API (SSH 22, HTTPS 443) through the first-boot firewall. This value and the controller's --management-cidr flag (T05/T06) must agree: both default to the cluster pod CIDR (10.244.0.0/16) and must be kept consistent. An empty value requires `allowOpenManagement=true` (fail-closed).
	// +kubebuilder:default:="10.244.0.0/16"
	ManagementCIDR string `json:"managementCIDR"`
	// Permit an empty `managementCIDR`, leaving the VyOS management API unrestricted (no first-boot firewall). Fail-closed by default: an empty `managementCIDR` with this false aborts rendering.
	// +kubebuilder:default:=false
	AllowOpenManagement bool `json:"allowOpenManagement"`
	// Opaque seed mixed into the VM firmware UUID. Change it to force a first-boot cloud-init re-run; clear it to preserve an existing VM's UUID across re-renders.
	// +kubebuilder:default:=""
	CloudInitSeed string `json:"cloudInitSeed,omitempty"`
}

type BGP struct {
	// Enable BGP peering.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Local autonomous system number.
	LocalASN int `json:"localASN,omitempty"`
	// BGP neighbors to peer with.
	Neighbors []BGPNeighbor `json:"neighbors,omitempty"`
}

type BGPNeighbor struct {
	// Neighbor IP address.
	Address string `json:"address"`
	// Remote autonomous system number of the neighbor.
	RemoteASN int `json:"remoteASN"`
}

type Image struct {
	// Import the boot disk over HTTP from `url` instead of cloning the golden-image PVC.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Golden image name in cozy-public. Cloned as the boot disk from PVC vm-default-images-<name> unless `enabled` is true.
	// +kubebuilder:default:="vyos-router"
	Name string `json:"name"`
	// HTTP(S) URL of a VyOS qcow2/raw disk image. Used only when `enabled` is true.
	// +kubebuilder:default:=""
	Url string `json:"url,omitempty"`
}

type Peer struct {
	// Public address (IP or hostname) of the remote peer. Responder model: the remote peer dials in.
	// +kubebuilder:default:=""
	Address string `json:"address"`
	// IPsec authentication material for the tunnel.
	// +kubebuilder:default:={}
	Auth PeerAuth `json:"auth,omitempty"`
}

type PeerAuth struct {
	// Name of an existing Secret in the tenant namespace holding the pre-shared key (key `psk`). Takes precedence over `psk` when set.
	ExistingSecret string `json:"existingSecret,omitempty"`
	// IPsec pre-shared key. Autogenerated and stored in a Secret when omitted. Mutually exclusive with `existingSecret`.
	Psk string `json:"psk,omitempty"`
}

type Resources struct {
	// CPU topology cores allocated to the router VM. Whole cores only; a fractional quantity (e.g. "1500m", "0.5") is rejected at admission rather than silently truncated to zero.
	// +kubebuilder:default:=2
	Cpu int `json:"cpu"`
	// Memory (RAM) allocated to the router VM.
	// +kubebuilder:default:="2Gi"
	Memory resource.Quantity `json:"memory"`
}

type StaticRoute struct {
	// Destination network in CIDR notation.
	Destination string `json:"destination"`
	// Next-hop IP address for the destination.
	NextHop string `json:"nextHop"`
}

type Tunnel struct {
	// Tunnel protocol used to connect to the remote peer.
	// +kubebuilder:default:="ipsec"
	Type TunnelType `json:"type"`
}

// +kubebuilder:validation:Enum="ipsec"
type TunnelType string
