// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package siterouter

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Site-to-site tunnel configuration.
	// +kubebuilder:default:={}
	Tunnel Tunnel `json:"tunnel"`
	// Remote peer this router builds a tunnel to.
	// +kubebuilder:default:={}
	Peer Peer `json:"peer"`
	// Remote networks reachable over the tunnel. Must be disjoint from the cluster pod/service/join networks (validated by the controller).
	// +kubebuilder:default:={}
	RemoteCIDRs []string `json:"remoteCIDRs,omitempty"`
	// Optional extra static routes programmed on the router.
	// +kubebuilder:default:={}
	StaticRoutes []StaticRoute `json:"staticRoutes,omitempty"`
	// Optional BGP peering over the tunnel. Disabled by default.
	// +kubebuilder:default:={}
	Bgp BGP `json:"bgp"`
	// Explicit CPU and memory sizing for the router VM.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
}

type BGP struct {
	// Enable BGP peering.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Local autonomous system number.
	LocalASN int `json:"localASN,omitempty"`
	// BGP neighbors to peer with.
	Neighbors []BGPNeighbor `json:"neighbors,omitempty"`
}

type BGPNeighbor struct {
	// Neighbor IP address.
	Address string `json:"address"`
	// Remote autonomous system number of the neighbor.
	RemoteASN int `json:"remoteASN"`
}

type Peer struct {
	// Public address (IP or hostname) of the remote peer. Responder model: the remote peer dials in.
	// +kubebuilder:default:=""
	Address string `json:"address"`
	// IPsec authentication material for the tunnel.
	// +kubebuilder:default:={}
	Auth PeerAuth `json:"auth,omitempty"`
}

type PeerAuth struct {
	// Name of an existing Secret in the tenant namespace holding the pre-shared key (key `psk`). Takes precedence over `psk` when set.
	ExistingSecret string `json:"existingSecret,omitempty"`
	// IPsec pre-shared key. Autogenerated and stored in a Secret when omitted. Mutually exclusive with `existingSecret`.
	Psk string `json:"psk,omitempty"`
}

type Resources struct {
	// CPU cores allocated to the router VM.
	// +kubebuilder:default:=2
	Cpu resource.Quantity `json:"cpu"`
	// Memory (RAM) allocated to the router VM.
	// +kubebuilder:default:="2Gi"
	Memory resource.Quantity `json:"memory"`
}

type StaticRoute struct {
	// Destination network in CIDR notation.
	Destination string `json:"destination"`
	// Next-hop IP address for the destination.
	NextHop string `json:"nextHop"`
}

type Tunnel struct {
	// Tunnel protocol used to connect to the remote peer.
	// +kubebuilder:default:="ipsec"
	Type TunnelType `json:"type"`
}

// +kubebuilder:validation:Enum="ipsec"
type TunnelType string
