//go:build !ignore_autogenerated

/*
Copyright 2025 The Cozystack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNS01) DeepCopyInto(out *CloudflareDNS01) {
	*out = *in
	in.APITokenSecretRef.DeepCopyInto(&out.APITokenSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNS01.
func (in *CloudflareDNS01) DeepCopy() *CloudflareDNS01 {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNS01)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS01Config) DeepCopyInto(out *DNS01Config) {
	*out = *in
	if in.Cloudflare != nil {
		in, out := &in.Cloudflare, &out.Cloudflare
		*out = new(CloudflareDNS01)
		(*in).DeepCopyInto(*out)
	}
	if in.Route53 != nil {
		in, out := &in.Route53, &out.Route53
		*out = new(Route53DNS01)
		(*in).DeepCopyInto(*out)
	}
	if in.DigitalOcean != nil {
		in, out := &in.DigitalOcean, &out.DigitalOcean
		*out = new(DigitalOceanDNS01)
		(*in).DeepCopyInto(*out)
	}
	if in.RFC2136 != nil {
		in, out := &in.RFC2136, &out.RFC2136
		*out = new(RFC2136DNS01)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS01Config.
func (in *DNS01Config) DeepCopy() *DNS01Config {
	if in == nil {
		return nil
	}
	out := new(DNS01Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigitalOceanDNS01) DeepCopyInto(out *DigitalOceanDNS01) {
	*out = *in
	in.TokenSecretRef.DeepCopyInto(&out.TokenSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigitalOceanDNS01.
func (in *DigitalOceanDNS01) DeepCopy() *DigitalOceanDNS01 {
	if in == nil {
		return nil
	}
	out := new(DigitalOceanDNS01)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RFC2136DNS01) DeepCopyInto(out *RFC2136DNS01) {
	*out = *in
	in.TSIGSecretSecretRef.DeepCopyInto(&out.TSIGSecretSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RFC2136DNS01.
func (in *RFC2136DNS01) DeepCopy() *RFC2136DNS01 {
	if in == nil {
		return nil
	}
	out := new(RFC2136DNS01)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53DNS01) DeepCopyInto(out *Route53DNS01) {
	*out = *in
	if in.SecretAccessKeySecretRef != nil {
		in, out := &in.SecretAccessKeySecretRef, &out.SecretAccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53DNS01.
func (in *Route53DNS01) DeepCopy() *Route53DNS01 {
	if in == nil {
		return nil
	}
	out := new(Route53DNS01)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPassthroughListener) DeepCopyInto(out *TLSPassthroughListener) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPassthroughListener.
func (in *TLSPassthroughListener) DeepCopy() *TLSPassthroughListener {
	if in == nil {
		return nil
	}
	out := new(TLSPassthroughListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGateway) DeepCopyInto(out *TenantGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGateway.
func (in *TenantGateway) DeepCopy() *TenantGateway {
	if in == nil {
		return nil
	}
	out := new(TenantGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGatewayList) DeepCopyInto(out *TenantGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGatewayList.
func (in *TenantGatewayList) DeepCopy() *TenantGatewayList {
	if in == nil {
		return nil
	}
	out := new(TenantGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGatewayListenerStatus) DeepCopyInto(out *TenantGatewayListenerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGatewayListenerStatus.
func (in *TenantGatewayListenerStatus) DeepCopy() *TenantGatewayListenerStatus {
	if in == nil {
		return nil
	}
	out := new(TenantGatewayListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGatewaySpec) DeepCopyInto(out *TenantGatewaySpec) {
	*out = *in
	if in.DNS01 != nil {
		in, out := &in.DNS01, &out.DNS01
		*out = new(DNS01Config)
		(*in).DeepCopyInto(*out)
	}
	if in.WildcardSecretRef != nil {
		in, out := &in.WildcardSecretRef, &out.WildcardSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.AttachedNamespaces != nil {
		in, out := &in.AttachedNamespaces, &out.AttachedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSPassthroughServices != nil {
		in, out := &in.TLSPassthroughServices, &out.TLSPassthroughServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSPassthroughListeners != nil {
		in, out := &in.TLSPassthroughListeners, &out.TLSPassthroughListeners
		*out = make([]TLSPassthroughListener, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGatewaySpec.
func (in *TenantGatewaySpec) DeepCopy() *TenantGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(TenantGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGatewayStatus) DeepCopyInto(out *TenantGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]TenantGatewayListenerStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGatewayStatus.
func (in *TenantGatewayStatus) DeepCopy() *TenantGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(TenantGatewayStatus)
	in.DeepCopyInto(out)
	return out
}
